### PR TITLE
Graphical board/stones customization interface #198

### PR DESCRIPTION
**Pull request by Seth-Rothschild**
Sorry on the delay. Something odd happened with pull/merge and this is my first time dealing with that. (notably: I have no idea how to clean up the double and triple copies of certain commits)

If there's anything further I can do to be helpful let me know.

### CODE REVIEW

**Comment by fohristiwhirl** [comment]
I think "Pallete" should be "Palette". Although maybe "Themes" would be better.

**Comment by yishn** [comment]
Thank you so much @Seth-Rothschild! Additionally, it would really help a lot if you can fix the formatting in your code.

**Comment by Seth-Rothschild** [comment]
@fohristiwhirl I think "Themes" is just as good. 
@yishn I'll give it a shot! I don't really know what I'm doing in that respect. Any advice from anyone would be helpful since I've never done it before.

**Comment by fohristiwhirl** [comment]
I believe yishn likes camelCase for variable names. :)

**Comment by yishn** [comment]
What I mean by formatting is a consistent 4 spaces indentation, no tabs, code in one block should have the same indentation. Currently, if you look at 'Files changed' here on Github, you'll see that it's all over the place.

**Comment by Seth-Rothschild** [comment]
Ah, it's good to know I'm not a totally crazy person. You're right that the files display looks nuts. Here's what it looks like in my editor. I'm probably _not_ going to fix the formatting for a couple of days since it involves either doing editor changes (of which I have a large list) or looking back and forth at how it presents itself on github. I'll have things cleaned up early next week to the best of my ability.
image

**Comment by yishn** [comment]
No pressure, take your time. My guess is you have your editor configured to use tabs instead of spaces. It should look fine if you convert tabs into spaces.

**Pull request merged**
